[build]
builder = "nixpacks"

[deploy]
startCommand = "cd web-app && npm install && cd client && npm install && npm run build && cd .. && node server.js"
healthcheckPath = "/"
healthcheckTimeout = 300

[env]
NODE_ENV = "production" 